PID: 20551
honu.cs.washington.edu
Job started at Wed Aug 21 13:49:49 PDT 2019
[RESOURCES] There are too many total processes running: 44!
[RESOURCES] There are too many total processes running: 41!
[RESOURCES] There are too many total processes running: 44!
Running patch plausibility analysis under Java-8 on the patch generated by DynaMoth for Bugs.jar::Jackrabbit-Oak-ba38c380::7
patch_plausibility.py script started at Wed Aug 21 13:50:51 PDT 2019
Switched to branch 'bugs-dot-jar_OAK-3089_ba38c380'
Reinitialized existing Git repository in /tmp/DynaMoth_Bugs.jar_Jackrabbit-Oak_ba38c380/.git/
Checking patch oak-core/src/main/java/org/apache/jackrabbit/oak/cache/CacheLIRS.java...
Applied patch oak-core/src/main/java/org/apache/jackrabbit/oak/cache/CacheLIRS.java cleanly.
There was no 'Please refer to (.*) for the individual test results.' in the maven log file!
Traceback (most recent call last):
  File "/scratch/rjust/critical_review_of_repair_them_all_data/plausibility/patch_plausibility.py", line 175, in <module>
    test, all_tests, failing_tests = utils.test(bugObj, CHECKOUT_DIR, java_home_dir, os.path.join(output_dir, "test.log"))
  File "/scratch/rjust/critical_review_of_repair_them_all_data/java_7_vs_java_8/utils.py", line 180, in test
    xml_files = collect_maven_surefire_xml_files(checkout_dir, rta_test_log_file)
  File "/scratch/rjust/critical_review_of_repair_them_all_data/java_7_vs_java_8/utils.py", line 258, in collect_maven_surefire_xml_files
    assert len(xml_files) > 0
AssertionError
Checkout Bugs.jar_Jackrabbit-Oak_ba38c380
Apply patch ...
Compile Bugs.jar_Jackrabbit-Oak_ba38c380
Run tests on Bugs.jar_Jackrabbit-Oak_ba38c380
patch_plausibility.py has failed!
