PID: 12277
honu.cs.washington.edu
Job started at Tue Aug 20 23:17:56 PDT 2019
Running patch plausibility analysis under Java-7 on the patch generated by Nopol for Bugs.jar::Flink-5308ac83::7
patch_plausibility.py script started at Tue Aug 20 23:17:57 PDT 2019
Switched to branch 'bugs-dot-jar_FLINK-1705_5308ac83'
Reinitialized existing Git repository in /tmp/Nopol_Bugs.jar_Flink_5308ac83/.git/
Checking patch flink-runtime/src/main/java/org/apache/flink/runtime/instance/InstanceConnectionInfo.java...
Applied patch flink-runtime/src/main/java/org/apache/flink/runtime/instance/InstanceConnectionInfo.java cleanly.
There was no 'Please refer to (.*) for the individual test results.' in the maven log file!
Traceback (most recent call last):
  File "/scratch/rjust/critical_review_of_repair_them_all_data/plausibility/patch_plausibility.py", line 175, in <module>
    test, all_tests, failing_tests = utils.test(bugObj, CHECKOUT_DIR, java_home_dir, os.path.join(output_dir, "test.log"))
  File "/scratch/rjust/critical_review_of_repair_them_all_data/java_7_vs_java_8/utils.py", line 183, in test
    xml_files = collect_maven_surefire_xml_files(checkout_dir, rta_test_log_file)
  File "/scratch/rjust/critical_review_of_repair_them_all_data/java_7_vs_java_8/utils.py", line 265, in collect_maven_surefire_xml_files
    assert len(xml_files) > 0
AssertionError
Checkout Bugs.jar_Flink_5308ac83
Apply patch ...
Compile Bugs.jar_Flink_5308ac83
Run tests on Bugs.jar_Flink_5308ac83
patch_plausibility.py has failed!
