PID: 34866
honu.cs.washington.edu
Job started at Tue Aug 20 23:55:31 PDT 2019
[RESOURCES] There are too many total processes running: 40!
[RESOURCES] There are too many total processes running: 38!
Running patch plausibility analysis under Java-7 on the patch generated by NPEFix for Bugs.jar::Jackrabbit-Oak-01f5a26f::0
patch_plausibility.py script started at Tue Aug 20 23:56:01 PDT 2019
Switched to branch 'bugs-dot-jar_OAK-3510_01f5a26f'
Picked up JAVA_TOOL_OPTIONS: -XX:CICompilerCount=2 -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2  
Reinitialized existing Git repository in /tmp/NPEFix_Bugs.jar_Jackrabbit-Oak_01f5a26f/.git/
Checking patch oak-auth-external/src/main/java/b/oak-auth-external/src/main/java/org/apache/jackrabbit/oak/spi/security/authentication/external/ExternalIdentityRef.java...
error: oak-auth-external/src/main/java/b/oak-auth-external/src/main/java/org/apache/jackrabbit/oak/spi/security/authentication/external/ExternalIdentityRef.java: No such file or directory
Traceback (most recent call last):
  File "/scratch/rjust/critical_review_of_repair_them_all_data/plausibility/patch_plausibility.py", line 158, in <module>
    zipdir(CHECKOUT_DIR, zipf)
  File "/scratch/rjust/critical_review_of_repair_them_all_data/plausibility/patch_plausibility.py", line 98, in zipdir
    ziph.write(os.path.join(root, file))
  File "/usr/lib64/python2.7/zipfile.py", line 1126, in write
    zinfo = ZipInfo(arcname, date_time)
  File "/usr/lib64/python2.7/zipfile.py", line 305, in __init__
    raise ValueError('ZIP does not support timestamps before 1980')
ValueError: ZIP does not support timestamps before 1980
Checkout Bugs.jar_Jackrabbit-Oak_01f5a26f
Apply patch ...
Compile top-level project
Get module information
patch_plausibility.py has failed!
