---
BugID: FLINK-2109
Summary: CancelTaskException leads to FAILED task state
Description: |-
  The {{CancelTaskException}} is thrown to trigger canceling of the executing task. It is intended to cause a cancelled status, rather than a failed status.

  Currently, it leads to a {{FAILED}} state instead of the expected {{CANCELED}} state.
